FORMAT: 1A
HOST: http://107.170.13.33:3000

# pebble-speaks-server
Pebble Speaks Server hosts speeches that you can run on your Pebble with Pebble Speaks.

# Group Speeches
Speeches related resources of the **Pebble Speaks API**

## Speeches Collection [/speeches]
### Retrieve all Speeches [GET]
+ Response 200 (application/json)

        [
          {
            "sections": [
              {
                "topic": "Kitties",
                "seconds": 60
              },
              {
                "topic": "Puppies",
                "seconds": 20
              }
            ],
            "title": "Favorite pets"
          },
          {
            "sections": [
              {
                "topic": "Facebook",
                "seconds": 60
              },
              {
                "topic": "Twitter",
                "seconds": 20
              },
              {
                "topic": "Pinterest",
                "seconds": 30
              }
            ],
            "title": "Online communities"
          },
          {
            "title": "Awesome foods",
            "sections": [
              {
                "seconds": 100,
                "topic": "Chaat"
              }
            ]
          }
        ]

### Create a Speech [POST]
+ Request (application/json)

        {
          "sections": [
            {
              "topic": "Kitties",
              "seconds": 60
            },
            {
              "topic": "Puppies",
              "seconds": 20
            }
          ],
          "title": "Favorite pets"
        }

+ Request (application/x-www-url-formencoded)

        speechData=%7B%22sections%22%3A%5B%7B%22topic%22%3A%22Kitties%22%2C%22seconds%22%3A60%7D%2C%7B%22topic%22%3A%22Puppies%22%2C%22seconds%22%3A20%7D%5D%7D

+ Response 200 (application/json)

        { "success": "Speech created!" }

## Speeches [/speeches/{speechNum}]
A single Note object with all its details

+ Parameters
    + speechNum (required, number, `0`) ... Index of the speech to perform action with.

### Retrieve a Speech [GET]
+ Response 200 (application/json)

    + Body

            {
              "sections": [
                {
                  "topic": "Kitties",
                  "seconds": 60
                },
                {
                  "topic": "Puppies",
                  "seconds": 20
                }
              ],
              "title": "Favorite pets"
            }

### Modify a Speech [PUT]
+ Request (application/json)

        {
          "sections": [
            {
              "topic": "Kitties",
              "seconds": 60
            },
            {
              "topic": "Puppies",
              "seconds": 20
            }
          ],
          "title": "Favorite pets"
        }

+ Request (application/x-www-url-formencoded)

        speechData=%7B%22sections%22%3A%5B%7B%22topic%22%3A%22Kitties%22%2C%22seconds%22%3A60%7D%2C%7B%22topic%22%3A%22Puppies%22%2C%22seconds%22%3A20%7D%5D%7D

+ Response 200 (application/json)

        { "success": "Speech 0 saved!" }

### Remove a Speech [DELETE]
+ Response 200 (application/json)

        { "success": "Speech 0 deleted!" }
